use customer_behaviour_analysis;
show tables;
select * from customer_data;

-- Q1) What is the total revenue generated by Men vs Women?
select gender, sum(purchase_amount) as revenue
from customer_data
group by gender;

-- Q2) Which customer used the discount but still spent the more amount than average purchase amount?
select customer_id, purchase_amount
from customer_data
where purchase_amount >= (select AVG(purchase_amount) from customer_data) and discount_applied = "Yes";

-- Q3) What are top 5 products with highest average review ratings?
select item_purchased, avg(review_rating) as "Avg Review Rating"
from customer_data
group by item_purchased
order by avg(review_rating) desc
Limit 5;

-- Q4) Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount)
from customer_data
where shipping_type in ("Standard", "Express")
group by shipping_type;

-- Q5) Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
       COUNT(customer_id) as total_customers,
       ROUND(avg(purchase_amount),2) as avg_spend,
       ROUND(sum(purchase_amount),2) as total_revenue
from customer_data
group by subscription_status
order by total_revenue,avg_spend DESC;

-- Q6) Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer_data
group by item_purchased
order by discount_rate DESC
limit 5;

-- Q7) Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END as customer_segment
from customer_data)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


-- Q8) What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    select category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    from customer_data
    group by category, item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- Q9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
       COUNT(customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status;

-- Q10) What is the revenue contribution of each age group? 
select 
    age_group,
    SUM(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;